extends Node
## Bus de signaux global.
## Les systèmes (joueur, monstre, UI, audio, énigmes) communiquent par ces signaux
## plutôt que de se référencer directement.

# --- Monde / gameplay ---
@warning_ignore("unused_signal")
signal noise_emitted(pos: Vector3, radius: float, source: String)
@warning_ignore("unused_signal")
signal scare_trigger(trigger_id: String, context: Node)
@warning_ignore("unused_signal")
signal monster_state_changed(state_name: String)
@warning_ignore("unused_signal")
signal monster_awakened()
@warning_ignore("unused_signal")
signal power_restored(group: String)
@warning_ignore("unused_signal")
signal register_burned()
@warning_ignore("unused_signal")
signal lightning_flash(strength: float)
@warning_ignore("unused_signal")
signal secret_opened()
@warning_ignore("unused_signal")
signal checkpoint_requested()
@warning_ignore("unused_signal")
signal ending_started(ending_id: String)

# --- Joueur ---
@warning_ignore("unused_signal")
signal player_caught()
@warning_ignore("unused_signal")
signal player_died()
@warning_ignore("unused_signal")
signal hide_state_changed(is_hidden: bool, kind: String)
@warning_ignore("unused_signal")
signal flashlight_changed(is_on: bool, charge: float)
@warning_ignore("unused_signal")
signal stamina_changed(value: float)
@warning_ignore("unused_signal")
signal camera_shake(amount: float)

# --- Interface ---
@warning_ignore("unused_signal")
signal interact_prompt_changed(text: String)
@warning_ignore("unused_signal")
signal message_requested(text: String, duration: float)
@warning_ignore("unused_signal")
signal objective_changed(text: String)
@warning_ignore("unused_signal")
signal note_requested(note_id: String)
@warning_ignore("unused_signal")
signal note_closed(note_id: String)
@warning_ignore("unused_signal")
signal keypad_requested(target: Node)
@warning_ignore("unused_signal")
signal screen_flash(color: Color, duration: float)
@warning_ignore("unused_signal")
signal screen_fade(to_alpha: float, duration: float)
@warning_ignore("unused_signal")
signal subtitle_requested(text: String, duration: float)
@warning_ignore("unused_signal")
signal checkpoint_saved()
@warning_ignore("unused_signal")
signal victory(ending_id: String)
@warning_ignore("unused_signal")
signal loading_progress(ratio: float, text: String)
